version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      - MONGO_HOST=mongo
      - TELEGRAM_TOKEN=6279332197:AAEd_wkFctbrd9vAki9etbh4T9kE5V9gvUs
    depends_on:
      - mongo
  mongo:
    image: mongo:4.0-xenial
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
